# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b90d26f879c2013115b2bc09f6077f737bb8a4f08228e5ea5b8c4a71f84438544c18b9e30aa3e8928f591f58ee920cca93dbe6da2dced13a36bff0fd509b9a

test:
  secret_key_base: ad9151b7ba99b05a33edea6463ee5bd98afc64788b4d565af44bbdb09df7f97f228f59e6ff3534b517baffb28e7bdf071a9310369573bfaa0f5d8cbeb46e67a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
